### ISSUE TITLE
Compare throughput when running two GoCBStorageEngines in parallel

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/go-couchbase-throughput#1]
@brett19 mentioned that he hasn't seen a benefit to holding more than one connection per CBS node when using gocb.  Running two GoCBStorageEngines in parallel should be a quick way to confirm that (at least for the single-key ops currently being tested by go-couchbase-throughput).

**Comment by tleyden** [comment]
Using these settings:

```
        totalNumDocs := 1000000
        docSizeBytes := 100
        numDocWriters := 100
        numDocReaders := 100
```

and this code:

```
        storageEngine1 := NewGoCBStorageEngine(url, bucket)
        storageEngine2 := NewGoCBStorageEngine(url, bucket)
        createDocWriters(docsToWrite, docsToRead, storageEngine1, numDocWriters)
        createDocReaders(docsToRead, docsFinished, storageEngine2, numDocReaders)
```

I'm seeing improved throughput (tried several times and got approx same results).

**2 GoCB storage engines**

<img width="813" alt="dual_gocb" src="https://cloud.githubusercontent.com/assets/296876/10230403/bdefc35e-6831-11e5-91b9-b6736dabd9d8.png">

**1 GoCB storage engine**

<img width="809" alt="single_gocb" src="https://cloud.githubusercontent.com/assets/296876/10230404/bdeff0ae-6831-11e5-9e88-0e3ae48ce131.png">
